services:
  - type: web
    name: asistencia-bomberos
    env: python
    buildCommand: ""
    startCommand: gunicorn app.app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: asistencia-db
          property: postgresql://postgres:postgres@localhost:5432/registrodb
      - key: SECRET_KEY
        value: ${SECRET_KEY}

databases:
  - name: asistencia-db
